# Generated by Django 6.0 on 2025-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='flag_icon',
            field=models.CharField(blank=True, help_text='Icon for target language', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='source_flag_icon',
            field=models.CharField(blank=True, help_text='Icon for source language (if specific)', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='source_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish')], help_text='Native language of the learner. If NULL, this is a Universal/Global course.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='target_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish')], max_length=5, null=True),
        ),
    ]
