# Generated by Django 5.0 on 2026-01-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_flag_icon_course_source_flag_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='kind',
            field=models.CharField(choices=[('KNOWLEDGE', 'Knowledge'), ('SKILL', 'Skill')], default='KNOWLEDGE', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='title_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
