# Generated by Django 6.0 on 2025-12-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=10)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConjugationActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('verb_infinitive', models.CharField(max_length=50)),
                ('tense', models.CharField(max_length=50)),
                ('pronoun', models.CharField(max_length=20)),
                ('correct_conjugation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Conjugation Activity',
                'verbose_name_plural': 'Conjugation Activities',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='DragOrderActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('words', models.JSONField(help_text='List of words/phrases to arrange')),
                ('correct_order', models.JSONField(help_text='Correct order (can be indices or the words themselves)')),
            ],
            options={
                'verbose_name': 'Drag & Order Activity',
                'verbose_name_plural': 'Drag & Order Activities',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='FillBlankActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('correct_answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fill The Blank Activity',
                'verbose_name_plural': 'Fill The Blank Activities',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='MatchingActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('pairs', models.JSONField(help_text='Dictionary of key-value pairs to match')),
            ],
            options={
                'verbose_name': 'Matching Activity',
                'verbose_name_plural': 'Matching Activities',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='MCQActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('choices', models.JSONField(help_text='List of strings for choices')),
                ('correct_answer_index', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Multiple Choice Activity',
                'verbose_name_plural': 'Multiple Choice Activities',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='MultipleAnswerActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('choices', models.JSONField(help_text='List of answer options')),
                ('correct_indices', models.JSONField(help_text='List of indices for all correct answers, e.g. [0, 2, 3]')),
            ],
            options={
                'verbose_name': 'Multiple Answer Activity',
                'verbose_name_plural': 'Multiple Answer Activities',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='TextInputActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('correct_answers', models.JSONField(help_text="List of acceptable answers, e.g. ['réponse1', 'réponse2']")),
                ('case_sensitive', models.BooleanField(default=False)),
                ('accept_partial', models.BooleanField(default=False, help_text='Accept partial matches')),
            ],
            options={
                'verbose_name': 'Text Input Activity',
                'verbose_name_plural': 'Text Input Activities',
            },
            bases=('activities.activity',),
        ),
    ]
