# Generated by Django 6.0 on 2025-12-28 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicteeActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('audio_urls', models.JSONField(help_text="List of audio file URLs (e.g., ['/media/audio/phrase_slow.mp3', '/media/audio/phrase_fast.mp3'])")),
                ('correct_text', models.CharField(help_text='The exact French text that should be typed', max_length=500)),
                ('case_sensitive', models.BooleanField(default=False, help_text='Whether to enforce case sensitivity in answer checking')),
            ],
            options={
                'verbose_name': 'Dictée Activity',
                'verbose_name_plural': 'Dictée Activities',
            },
            bases=('activities.activity',),
        ),
        migrations.AddField(
            model_name='activity',
            name='explanation_key',
            field=models.CharField(blank=True, help_text='i18n key for explanation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='question_text_key',
            field=models.CharField(blank=True, help_text="i18n key for question (e.g., 'activity.fill_blank.instruction')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='translation_data',
            field=models.JSONField(blank=True, default=dict, help_text="Parameters for interpolation (e.g., {'phrase': 'Je suis ___'})"),
        ),
        migrations.AddField(
            model_name='matchingactivity',
            name='values_are_translatable',
            field=models.BooleanField(default=False, help_text='True if values are translation keys, False if literal text'),
        ),
        migrations.AddField(
            model_name='mcqactivity',
            name='choices_are_translatable',
            field=models.BooleanField(default=False, help_text='True for Cases B & C (translated choices), False for Case A (French choices)'),
        ),
        migrations.AddField(
            model_name='mcqactivity',
            name='choices_keys',
            field=models.JSONField(blank=True, help_text="Translation keys for choices (e.g., ['word.apple', 'word.orange'])", null=True),
        ),
        migrations.AddField(
            model_name='multipleansweractivity',
            name='choices_are_translatable',
            field=models.BooleanField(default=False, help_text="True if choices should be translated to learner's language"),
        ),
        migrations.AddField(
            model_name='multipleansweractivity',
            name='choices_keys',
            field=models.JSONField(blank=True, help_text='Translation keys for choices (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='dragorderactivity',
            name='correct_order',
            field=models.JSONField(help_text='Correct order (indices or words)'),
        ),
        migrations.AlterField(
            model_name='dragorderactivity',
            name='words',
            field=models.JSONField(help_text='List of words/phrases to arrange (in French)'),
        ),
        migrations.AlterField(
            model_name='matchingactivity',
            name='pairs',
            field=models.JSONField(help_text="Dictionary of pairs. For translatable values, prefix with 'key:' (e.g., {'le chat': 'key:animal.cat'})"),
        ),
        migrations.AlterField(
            model_name='mcqactivity',
            name='choices',
            field=models.JSONField(help_text='List of choice strings (French for Case A)'),
        ),
        migrations.AlterField(
            model_name='multipleansweractivity',
            name='correct_indices',
            field=models.JSONField(help_text='List of indices for all correct answers'),
        ),
        migrations.AlterField(
            model_name='textinputactivity',
            name='correct_answers',
            field=models.JSONField(help_text='List of acceptable answers in French'),
        ),
    ]
