# Generated by Django 6.0 on 2026-01-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_dicteeactivity_activity_explanation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicteeactivity',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload an audio file here to automatically add it to audio_urls', null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='dicteeactivity',
            name='audio_urls',
            field=models.JSONField(blank=True, default=list, help_text="List of audio file URLs (e.g., ['/media/audio/phrase_slow.mp3', '/media/audio/phrase_fast.mp3'])"),
        ),
    ]
