# Generated by Django 5.0 on 2026-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_activity_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='supported_ui_languages',
            field=models.JSONField(blank=True, default=list, help_text="List of UI languages this activity supports when it contains translated content (e.g., ['en','ar']). Empty means universal (doesn't depend on UI language)."),
        ),
        migrations.AddField(
            model_name='matchingactivity',
            name='pairs_i18n',
            field=models.JSONField(blank=True, default=dict, help_text="Teacher-provided multilingual pairs. Keys are typically French terms; values are dicts keyed by UI language code (e.g. {'en': 'perfect', 'ar': 'ممتاز'}). If a language is missing for any entry, exclude it from supported_ui_languages."),
        ),
        migrations.AddField(
            model_name='mcqactivity',
            name='choices_i18n',
            field=models.JSONField(blank=True, default=list, help_text="Optional multilingual choices provided by teacher. Each choice is a dict keyed by language code. Use supported_ui_languages to prevent serving when the user's UI language is missing."),
        ),
        migrations.AddField(
            model_name='multipleansweractivity',
            name='choices_i18n',
            field=models.JSONField(blank=True, default=list, help_text='Optional multilingual choices provided by teacher. Each choice is a dict keyed by language code.'),
        ),
    ]
