# Generated by Django 5.0 on 2026-01-13 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_supported_ui_languages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='Last person who modified this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
