# Generated by Django 5.0 on 2026-01-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_modified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillblankactivity',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='fillblankactivity',
            name='phrase',
            field=models.TextField(blank=True, help_text="Sentence containing blank(s), e.g. 'Je ___ à l'école.'", null=True),
        ),
        migrations.AddField(
            model_name='fillblankactivity',
            name='phrase_key',
            field=models.CharField(blank=True, help_text='i18n key for the phrase', max_length=255, null=True),
        ),
    ]
