# Generated by Django 5.0 on 2026-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_fillblankactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instruction_key',
            field=models.CharField(blank=True, help_text="i18n key for general instruction (e.g., 'activity.mcq.instruction')", max_length=255, null=True),
        ),
    ]
