# Generated by Django 5.0 on 2026-01-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_instruction_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingactivity',
            name='pairs_v2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='activity',
            name='instruction_key',
            field=models.CharField(blank=True, help_text="i18n key for general instruction (e.g., 'activity.mcq.instruction', 'activity.dictee.instruction')", max_length=255, null=True),
        ),
    ]
