# Generated by Django 5.0 on 2026-01-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_matchingactivity_pairs_v2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqactivity',
            name='choices_v2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mcqactivity',
            name='correct_choice_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='multipleansweractivity',
            name='choices_v2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='multipleansweractivity',
            name='correct_choice_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
