# Generated by Django 5.0 on 2026-01-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_mcqactivity_choices_v2_mcqactivity_correct_choice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='matchingactivity',
            name='pairs',
        ),
        migrations.RemoveField(
            model_name='matchingactivity',
            name='pairs_i18n',
        ),
        migrations.RemoveField(
            model_name='matchingactivity',
            name='values_are_translatable',
        ),
        migrations.RemoveField(
            model_name='mcqactivity',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='mcqactivity',
            name='choices_are_translatable',
        ),
        migrations.RemoveField(
            model_name='mcqactivity',
            name='choices_i18n',
        ),
        migrations.RemoveField(
            model_name='mcqactivity',
            name='choices_keys',
        ),
        migrations.RemoveField(
            model_name='mcqactivity',
            name='correct_answer_index',
        ),
        migrations.RemoveField(
            model_name='multipleansweractivity',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='multipleansweractivity',
            name='choices_are_translatable',
        ),
        migrations.RemoveField(
            model_name='multipleansweractivity',
            name='choices_i18n',
        ),
        migrations.RemoveField(
            model_name='multipleansweractivity',
            name='choices_keys',
        ),
        migrations.RemoveField(
            model_name='multipleansweractivity',
            name='correct_indices',
        ),
    ]
