# Generated by Django 6.0 on 2025-12-25 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedActivityQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_failed_at', models.DateTimeField(auto_now_add=True)),
                ('times_failed', models.PositiveIntegerField(default=1)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Failed Activity Queue',
                'verbose_name_plural': 'Failed Activity Queue',
                'ordering': ['-priority', 'first_failed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('MIXED', 'Mixed (All Subjects)'), ('SUBJECT_FOCUSED', 'Subject Focused'), ('CUSTOM', 'Custom Practice')], default='MIXED', max_length=20)),
                ('target_activities', models.PositiveIntegerField(default=30)),
                ('activities_completed', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed (>=80%)'), ('RETRY', 'Needs Retry (50-79%)'), ('DOWNGRADE', 'Downgrade Recommended (<50%)'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('set_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('is_weak_area', models.BooleanField(default=False)),
                ('needs_focus', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subject Performance Snapshot',
                'verbose_name_plural': 'Subject Performance Snapshots',
                'ordering': ['accuracy_percentage'],
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=10)),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('completed_activities', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Progress',
                'verbose_name_plural': 'Subject Progress',
                'ordering': ['subject', 'level__order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=10)),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('completed_activities', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('current_session_correct', models.PositiveIntegerField(default=0)),
                ('current_session_total', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'ordering': ['level__order'],
            },
        ),
        migrations.CreateModel(
            name='WeaknessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_analyzed', models.PositiveIntegerField()),
                ('average_accuracy', models.FloatField()),
                ('severity', models.CharField(choices=[('MINOR', 'Minor Issue'), ('MODERATE', 'Needs Attention'), ('CRITICAL', 'Critical - Needs Focus')], max_length=10)),
                ('message', models.TextField()),
                ('recommendation', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weakness Alert',
                'verbose_name_plural': 'Weakness Alerts',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Activity Attempt',
                'verbose_name_plural': 'Activity Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
