# Generated by Django 6.0 on 2025-12-25 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('courses', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectperformancesnapshot',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
        migrations.AddField(
            model_name='subjectperformancesnapshot',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_breakdown', to='progress.studysession'),
        ),
        migrations.AddField(
            model_name='subjectperformancesnapshot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='subjectperformancesnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weaknessalert',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
        migrations.AddField(
            model_name='weaknessalert',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='weaknessalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakness_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityattempt',
            index=models.Index(fields=['user', 'activity', '-attempted_at'], name='progress_ac_user_id_7ce78f_idx'),
        ),
        migrations.AddIndex(
            model_name='activityattempt',
            index=models.Index(fields=['user', '-attempted_at'], name='progress_ac_user_id_ac739f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='failedactivityqueue',
            unique_together={('user', 'activity')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectperformancesnapshot',
            unique_together={('session', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectprogress',
            unique_together={('user', 'subject', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='weaknessalert',
            unique_together={('user', 'level', 'subject')},
        ),
    ]
