# Generated by Django 6.0 on 2025-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='initial_activity_queue',
            field=models.JSONField(blank=True, help_text='List of activity IDs for deterministic replay', null=True),
        ),
    ]
