# Generated by Django 5.0 on 2026-01-08 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_activity_is_approved_and_more'),
        ('courses', '0003_course_flag_icon_course_source_flag_icon_and_more'),
        ('progress', '0003_studysession_initial_activity_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='activityattempt',
            name='progress_ac_user_id_7ce78f_idx',
        ),
        migrations.RemoveIndex(
            model_name='activityattempt',
            name='progress_ac_user_id_ac739f_idx',
        ),
        migrations.AddField(
            model_name='activityattempt',
            name='client_attempt_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='interval_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='last_outcome',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='next_review_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='failedactivityqueue',
            name='times_reviewed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='completion_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='completion_xp_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='activityattempt',
            index=models.Index(fields=['user', 'attempted_at'], name='progress_ac_user_id_cffc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityattempt',
            index=models.Index(fields=['session_id'], name='progress_ac_session_843144_idx'),
        ),
        migrations.AddIndex(
            model_name='activityattempt',
            index=models.Index(fields=['user', 'activity'], name='progress_ac_user_id_eb8c28_idx'),
        ),
        migrations.AddIndex(
            model_name='failedactivityqueue',
            index=models.Index(fields=['user', 'next_review_at'], name='progress_fa_user_id_7e39dd_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'outcome'], name='progress_st_user_id_7097f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'level', 'subject'], name='progress_st_user_id_64a9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'started_at'], name='progress_st_user_id_91a6b5_idx'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='progress.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
