# Generated by Django 5.0 on 2026-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_achievement_userachievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(choices=[('MIXED', 'Mixed (All Subjects)'), ('SUBJECT_FOCUSED', 'Subject Focused'), ('CUSTOM', 'Custom Practice'), ('REHEARSAL_MISSED', 'Rehearsal (Missed Only - No Progress)')], default='MIXED', max_length=20),
        ),
    ]
