# Generated by Django 5.0 on 2026-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_native_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='can_publish_directly',
            field=models.BooleanField(default=False, help_text='Can publish activities without admin approval'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_practice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_permission_level',
            field=models.CharField(choices=[('NONE', 'Not a Teacher'), ('BASIC', 'Basic Creator'), ('VERIFIED', 'Verified Creator'), ('LEAD', 'Lead Teacher')], default='NONE', help_text="Teacher's content creation permission level", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_practice_date'], name='users_user_last_pr_438012_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['teacher_permission_level'], name='users_user_teacher_00870c_idx'),
        ),
    ]
